# Generated by Django 6.0.2 on 2026-02-12 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Nombre completo del cliente', max_length=150, verbose_name='Nombre del cliente')),
                ('client_phone', models.CharField(help_text='Número de contacto para confirmaciones y recordatorios', max_length=20, verbose_name='Teléfono del cliente')),
                ('client_email', models.EmailField(blank=True, help_text='Email opcional para notificaciones', max_length=254, null=True, verbose_name='Email del cliente')),
                ('service_name', models.CharField(help_text='Nombre del servicio a realizar (ej: Corte de cabello, Manicure, etc.)', max_length=200, verbose_name='Servicio')),
                ('service_duration', models.PositiveIntegerField(default=30, help_text='Duración estimada del servicio en minutos', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duración (minutos)')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Precio del servicio en moneda local', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('appointment_date', models.DateField(help_text='Día en que se realizará la cita', verbose_name='Fecha de la cita')),
                ('appointment_time', models.TimeField(help_text='Hora de inicio de la cita', verbose_name='Hora de la cita')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No asistió')], default='pending', help_text='Estado actual de la cita', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales, preferencias del cliente o instrucciones especiales', verbose_name='Notas')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Razón por la cual se canceló la cita (si aplica)', verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la cita en el sistema', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['appointment_date', 'appointment_time'],
                'permissions': [('can_confirm_appointment', 'Puede confirmar citas'), ('can_cancel_appointment', 'Puede cancelar citas'), ('can_view_all_appointments', 'Puede ver todas las citas')],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_c5b816_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['client_phone'], name='appointment_client__dc501c_idx')],
            },
        ),
    ]
