# Generated by Django 6.0.2 on 2026-02-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Negocio al que pertenece esta cita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente del negocio (CRM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, help_text='Profesional asignado a esta cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.professional'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Servicio configurado del negocio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.service'),
        ),
    ]
