# Generated by Django 6.0.2 on 2026-04-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_business_appointment_client_and_more'),
        ('business', '0003_alter_user_managers_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_created', 'Cita Creada'), ('appointment_confirmed', 'Cita Confirmada'), ('appointment_cancelled', 'Cita Cancelada'), ('appointment_rescheduled', 'Cita Reprogramada'), ('appointment_reminder', 'Recordatorio de Cita'), ('appointment_completed', 'Cita Completada'), ('appointment_no_show', 'Cliente No Asistió'), ('system_update', 'Actualización del Sistema'), ('payment_received', 'Pago Recibido'), ('client_registered', 'Nuevo Cliente Registrado')], help_text='Categoría de la notificación', max_length=50, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(help_text='Título breve de la notificación', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Contenido completo de la notificación', verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si el usuario ya leyó esta notificación', verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se marcó como leída', null=True, verbose_name='Leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación', verbose_name='Creada el')),
                ('appointment', models.ForeignKey(blank=True, help_text='Cita relacionada con esta notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('business', models.ForeignKey(help_text='Negocio al que pertenece esta notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.business')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario destinatario (None = todos los usuarios del negocio)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'user', 'is_read'], name='appointment_busines_2b50f9_idx'), models.Index(fields=['business', 'created_at'], name='appointment_busines_3cfb5b_idx'), models.Index(fields=['notification_type'], name='appointment_notific_0c936f_idx')],
            },
        ),
    ]
