# Generated by Django 6.0.2 on 2026-04-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_add_onboarding_progress_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: "Resumen Semanal de Citas"', max_length=200, verbose_name='Nombre del Template')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de qué incluye el reporte', verbose_name='Descripción')),
                ('category', models.CharField(choices=[('appointments', 'Citas'), ('revenue', 'Ingresos'), ('clients', 'Clientes'), ('professionals', 'Profesionales'), ('operations', 'Operaciones'), ('custom', 'Personalizado')], default='appointments', help_text='Categoría principal del reporte', max_length=50, verbose_name='Categoría')),
                ('config', models.JSONField(default=dict, help_text='Configuración JSON del template (métricas, periodo, visualizaciones)', verbose_name='Configuración')),
                ('is_system', models.BooleanField(default=False, help_text='Templates del sistema no pueden ser editados por usuarios', verbose_name='¿Es del Sistema?')),
                ('order', models.IntegerField(default=0, help_text='Orden de presentación (menor = primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Reporte',
                'verbose_name_plural': 'Templates de Reportes',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: "Citas de Enero 2024"', max_length=200, verbose_name='Nombre del Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('config', models.JSONField(default=dict, help_text='Filtros y configuración específica del reporte', verbose_name='Configuración')),
                ('is_favorite', models.BooleanField(default=False, help_text='Marcar para acceso rápido', verbose_name='¿Favorito?')),
                ('is_scheduled', models.BooleanField(default=False, help_text='Enviar automáticamente por email', verbose_name='¿Programado?')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, null=True, verbose_name='Frecuencia de Envío')),
                ('schedule_recipients', models.JSONField(blank=True, default=list, help_text='Lista de emails para envío automático', verbose_name='Destinatarios')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Generación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='business.business', verbose_name='Negocio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(blank=True, help_text='Template del que se derivó este reporte (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='reports.reporttemplate', verbose_name='Template Base')),
            ],
            options={
                'verbose_name': 'Reporte Guardado',
                'verbose_name_plural': 'Reportes Guardados',
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato')),
                ('file_name', models.CharField(help_text='Nombre del archivo generado', max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True, verbose_name='Tamaño (bytes)')),
                ('file_path', models.CharField(blank=True, help_text='Path relativo al MEDIA_ROOT', max_length=500, verbose_name='Ruta del Archivo')),
                ('config', models.JSONField(default=dict, help_text='Parámetros usados para generar el reporte', verbose_name='Configuración')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional (ej: cantidad de registros, tiempo de generación)', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Exportación')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to='business.business', verbose_name='Negocio')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='Exportado por')),
                ('saved_report', models.ForeignKey(blank=True, help_text='Si se exportó desde un reporte guardado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports.savedreport', verbose_name='Reporte Guardado')),
            ],
            options={
                'verbose_name': 'Historial de Exportación',
                'verbose_name_plural': 'Historial de Exportaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='reports_exp_busines_f9b3c5_idx'), models.Index(fields=['exported_by', '-created_at'], name='reports_exp_exporte_cede52_idx')],
            },
        ),
    ]
