# Generated by Django 6.0.2 on 2026-04-07 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_created_service', models.BooleanField(default=False, help_text='Ha creado al menos un servicio', verbose_name='Servicio Creado')),
                ('has_configured_hours', models.BooleanField(default=False, help_text='Ha configurado los horarios de atención', verbose_name='Horarios Configurados')),
                ('has_created_professional', models.BooleanField(default=False, help_text='Ha agregado al menos un profesional', verbose_name='Profesional Agregado')),
                ('has_customized_branding', models.BooleanField(default=False, help_text='Ha personalizado logo o colores', verbose_name='Branding Personalizado')),
                ('has_created_first_appointment', models.BooleanField(default=False, help_text='Ha creado su primera cita', verbose_name='Primera Cita Creada')),
                ('has_invited_team_member', models.BooleanField(default=False, help_text='Ha invitado a un miembro del equipo (opcional)', verbose_name='Miembro Invitado')),
                ('has_tested_public_booking', models.BooleanField(default=False, help_text='Ha probado el portal de reservas público', verbose_name='Portal Probado')),
                ('is_completed', models.BooleanField(default=False, help_text='Indica si el onboarding está completo', verbose_name='Onboarding Completado')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Usuario decidió omitir el onboarding', verbose_name='Onboarding Omitido')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el onboarding', null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(help_text='Negocio asociado a este progreso', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='business.business')),
            ],
            options={
                'verbose_name': 'Progreso de Onboarding',
                'verbose_name_plural': 'Progresos de Onboarding',
                'db_table': 'onboarding_progress',
            },
        ),
    ]
