# Generated by Django 6.0.2 on 2026-04-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_add_onboarding_progress_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_max_days_ahead',
            field=models.IntegerField(default=60, help_text='Días máximos a futuro para reservar'),
        ),
        migrations.AddField(
            model_name='business',
            name='booking_min_notice_hours',
            field=models.IntegerField(default=2, help_text='Anticipación mínima para reservar'),
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_online_bookable', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad se evalúa primero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='business.business')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='business.professional')),
            ],
            options={
                'verbose_name': 'Regla de Disponibilidad',
                'verbose_name_plural': 'Reglas de Disponibilidad',
                'db_table': 'availability_rules',
                'ordering': ['business', 'professional', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exception_type', models.CharField(choices=[('blocked', 'Bloqueado'), ('available', 'Disponible')], default='blocked', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='business.business')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='business.professional')),
            ],
            options={
                'verbose_name': 'Excepción de Disponibilidad',
                'verbose_name_plural': 'Excepciones de Disponibilidad',
                'db_table': 'availability_exceptions',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['business', 'date'], name='availabilit_busines_98167c_idx'), models.Index(fields=['professional', 'date'], name='availabilit_profess_cdc331_idx')],
            },
        ),
    ]
