# Generated by Django 6.0.2 on 2026-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0005_business_booking_max_days_ahead_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['business', 'weekday'], name='availabilit_busines_5aa4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['professional', 'weekday'], name='availabilit_profess_b8df5d_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['business', 'is_active'], name='availabilit_busines_953d70_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='businesses_slug_279d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'created_at'], name='businesses_is_acti_92bb33_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['current_plan'], name='businesses_current_51ad58_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type'], name='businesses_busines_230284_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['business', 'is_active'], name='professiona_busines_8200a0_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['user'], name='professiona_user_id_4cf27e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['business', 'is_active'], name='services_busines_302365_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business', 'role'], name='users_busines_b86a75_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
